-- ESIM.dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA GO

CREATE TABLE ESIM.dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA (
	CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCAID int IDENTITY(1,1) NOT NULL,
	CALENDARIOCONVENIOID int NOT NULL,
	LOTEMOVIMENTACAOCOBRANCAID bigint NOT NULL,
	CONSTRAINT PK_CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA PRIMARY KEY (CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCAID)
) GO
 CREATE NONCLUSTERED INDEX IX_FK_CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA_CALENDARIOCONVENIO ON dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA (  CALENDARIOCONVENIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA_LOTEMOVIMENTACAOCOBRANCA ON dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA (  LOTEMOVIMENTACAOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA foreign keys

ALTER TABLE ESIM.dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA ADD CONSTRAINT FK_CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA_CALENDARIOCONVENIO FOREIGN KEY (CALENDARIOCONVENIOID) REFERENCES ESIM.dbo.CALENDARIOCONVENIO(CALENDARIOCONVENIOID) GO
ALTER TABLE ESIM.dbo.CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA ADD CONSTRAINT FK_CALENDARIOCONVENIOLOTEMOVIMENTACAOCOBRANCA_LOTEMOVIMENTACAOCOBRANCA FOREIGN KEY (LOTEMOVIMENTACAOCOBRANCAID) REFERENCES ESIM.dbo.LOTEMOVIMENTACAOCOBRANCA(LOTEMOVIMENTACAOCOBRANCAID) GO;