-- ESIM.dbo.COBRANCAINDIVIDUAL definition

-- Drop table

-- DROP TABLE ESIM.dbo.COBRANCAINDIVIDUAL GO

CREATE TABLE ESIM.dbo.COBRANCAINDIVIDUAL (
	COBRANCAINDIVIDUALID bigint IDENTITY(1,1) NOT NULL,
	FORMACOBRANCAID smallint NOT NULL,
	TIPOCOBRANCAINDIVIDUALID smallint NOT NULL,
	COMPETENCIA date NOT NULL,
	CONVENIOID smallint NULL,
	TIPORELACIONAMENTOID smallint NULL,
	DIAVENCIMENTO smallint NULL,
	MATRICULAID bigint NULL,
	ENDERECOID int NULL,
	EMAILID int NULL,
	NOMEPESSOA varchar(200) COLLATE Latin1_General_CI_AI NULL,
	CPF numeric(14,0) NULL,
	ORGAOCONSIGNANTE_PESSOAID int NULL,
	MATRICULAFUNCIONAL varchar(15) COLLATE Latin1_General_CI_AI NULL,
	TIPORUBRICACOBRANCAID smallint NULL,
	CONTACORRENTEID int NULL,
	FUNCIONARIOORGAOCONSIGNANTEID int NULL,
	IDENTIFICADORCARTAOCREDITO bigint NULL,
	VALORTOTAL numeric(14,2) NULL,
	VALORPAGO numeric(14,2) NULL,
	STATUSCOBRANCAINDIVIDUALID smallint NULL,
	CNPJ numeric(15,0) NULL,
	DATAHORACRIACAO datetime2(7) NULL,
	DATAVENCIMENTO date NULL,
	VALORTOTALIOF numeric(14,2) NULL,
	DATAESPERADACREDITO date NULL,
	CALENDARIOGRUPOCOBRANCAID int NULL,
	CALENDARIOCONVENIOID int NULL,
	CHAVENATURAL varchar(50) COLLATE Latin1_General_CI_AI DEFAULT '' NOT NULL,
	ENVIADOEVENTO numeric(1,0) DEFAULT 0 NOT NULL,
	VALORMULTA numeric(14,2) NULL,
	VALORMORA numeric(14,2) NULL,
	CONSTRAINT PK_COBRANCAINDIVIDUAL PRIMARY KEY (COBRANCAINDIVIDUALID)
) GO
 CREATE NONCLUSTERED INDEX AK_COBRANCAINDIVIDUAL ON dbo.COBRANCAINDIVIDUAL (  CHAVENATURAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IN_COBRANCAINDIVIDUALDESCONTOFOLHA ON dbo.COBRANCAINDIVIDUAL (  ORGAOCONSIGNANTE_PESSOAID ASC  , MATRICULAFUNCIONAL ASC  , TIPORUBRICACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_DATAVENCIMENTO ON dbo.COBRANCAINDIVIDUAL (  DATAVENCIMENTO ASC  , FORMACOBRANCAID ASC  , TIPOCOBRANCAINDIVIDUALID ASC  )  
	 INCLUDE ( CONVENIOID ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_CALENDARIOCONVENIO ON dbo.COBRANCAINDIVIDUAL (  CALENDARIOCONVENIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_CALENDARIOGRUPOCOBRANCA ON dbo.COBRANCAINDIVIDUAL (  CALENDARIOGRUPOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_CLIENTE ON dbo.COBRANCAINDIVIDUAL (  MATRICULAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_CONTACORRENTE ON dbo.COBRANCAINDIVIDUAL (  CONTACORRENTEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_CONVENIO ON dbo.COBRANCAINDIVIDUAL (  CONVENIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_EMAIL ON dbo.COBRANCAINDIVIDUAL (  EMAILID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_ENDERECO ON dbo.COBRANCAINDIVIDUAL (  ENDERECOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_FORMACOBRANCA ON dbo.COBRANCAINDIVIDUAL (  FORMACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_FUNCIONARIOORGAOCONSIGNANTE ON dbo.COBRANCAINDIVIDUAL (  FUNCIONARIOORGAOCONSIGNANTEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_ORGAOCONSIGNANTE ON dbo.COBRANCAINDIVIDUAL (  ORGAOCONSIGNANTE_PESSOAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_STATUSCOBRANCAINDIVIDUAL ON dbo.COBRANCAINDIVIDUAL (  STATUSCOBRANCAINDIVIDUALID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_TIPOCOBRANCAINDIVIDUAL ON dbo.COBRANCAINDIVIDUAL (  TIPOCOBRANCAINDIVIDUALID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_TIPORELACIONAMENTO ON dbo.COBRANCAINDIVIDUAL (  TIPORELACIONAMENTOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCAINDIVIDUAL_TIPORUBRICACOBRANCA ON dbo.COBRANCAINDIVIDUAL (  TIPORUBRICACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.COBRANCAINDIVIDUAL foreign keys

ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_CALENDARIOCONVENIO FOREIGN KEY (CALENDARIOCONVENIOID) REFERENCES ESIM.dbo.CALENDARIOCONVENIO(CALENDARIOCONVENIOID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_CALENDARIOGRUPOCOBRANCA FOREIGN KEY (CALENDARIOGRUPOCOBRANCAID) REFERENCES ESIM.dbo.CALENDARIOGRUPOCOBRANCA(CALENDARIOGRUPOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_CLIENTE FOREIGN KEY (MATRICULAID) REFERENCES ESIM.dbo.CLIENTE(MATRICULAID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_CONTACORRENTE FOREIGN KEY (CONTACORRENTEID) REFERENCES ESIM.dbo.CONTACORRENTE(CONTACORRENTEID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_CONVENIO FOREIGN KEY (CONVENIOID) REFERENCES ESIM.dbo.CONVENIO(CONVENIOID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_EMAIL FOREIGN KEY (EMAILID) REFERENCES ESIM.dbo.EMAIL(EMAILID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_ENDERECO FOREIGN KEY (ENDERECOID) REFERENCES ESIM.dbo.ENDERECO(ENDERECOID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_FORMACOBRANCA FOREIGN KEY (FORMACOBRANCAID) REFERENCES ESIM.dbo.FORMACOBRANCA(FORMACOBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_FUNCIONARIOORGAOCONSIGNANTE FOREIGN KEY (FUNCIONARIOORGAOCONSIGNANTEID) REFERENCES ESIM.dbo.FUNCIONARIOORGAOCONSIGNANTE(FUNCIONARIOORGAOCONSIGNANTEID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_ORGAOCONSIGNANTE FOREIGN KEY (ORGAOCONSIGNANTE_PESSOAID) REFERENCES ESIM.dbo.ORGAOCONSIGNANTE(ORGAOCONSIGNANTE_PESSOAID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_STATUSCOBRANCAINDIVIDUAL FOREIGN KEY (STATUSCOBRANCAINDIVIDUALID) REFERENCES ESIM.dbo.STATUSCOBRANCAINDIVIDUAL(STATUSCOBRANCAINDIVIDUALID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_TIPOCOBRANCAINDIVIDUAL FOREIGN KEY (TIPOCOBRANCAINDIVIDUALID) REFERENCES ESIM.dbo.TIPOCOBRANCAINDIVIDUAL(TIPOCOBRANCAINDIVIDUALID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_TIPORELACIONAMENTO FOREIGN KEY (TIPORELACIONAMENTOID) REFERENCES ESIM.dbo.TIPORELACIONAMENTO(TIPORELACIONAMENTOID) GO
ALTER TABLE ESIM.dbo.COBRANCAINDIVIDUAL ADD CONSTRAINT FK_COBRANCAINDIVIDUAL_TIPORUBRICACOBRANCA FOREIGN KEY (TIPORUBRICACOBRANCAID) REFERENCES ESIM.dbo.TIPORUBRICACOBRANCA(TIPORUBRICACOBRANCAID) GO;