-- ESIM.dbo.HISTORICOFORMACOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.HISTORICOFORMACOBRANCA GO

CREATE TABLE ESIM.dbo.HISTORICOFORMACOBRANCA (
	HISTORICOFORMACOBRANCAID bigint IDENTITY(1,1) NOT NULL,
	INSCRICAOID bigint NOT NULL,
	COMPETENCIAINICIAL date NOT NULL,
	COMPETENCIAFINAL date NOT NULL,
	DIAVENCIMENTO smallint NULL,
	PRIMARIA_FORMACOBRANCAID smallint NOT NULL,
	SECUNDARIA_FORMACOBRANCAID smallint NULL,
	FUNCIONARIOORGAOCONSIGNANTEID int NULL,
	CONTACORRENTEID int NULL,
	ORGAOCONSIGNANTEDEBITOCONTA_PESSOAID int NULL,
	TIPORUBRICACOBRANCAID smallint NULL,
	ORGAOCONSIGNANTE_PESSOAID int NULL,
	FUNCIONARIOINSTITUIDORID int NULL,
	FUNCIONARIOCONVENIOPARCERIAID int NULL,
	FUNCIONARIOCONVENIOCOBRANCAID int NULL,
	IDENTIFICADORCARTAOCREDITO bigint NULL,
	CONVENIOID smallint NULL,
	PERIODICIDADEID smallint NOT NULL,
	TIPOAGRUPAMENTOCOBRANCAID smallint NOT NULL,
	NUMEROPREAUTORIZACAO varchar(8) COLLATE Latin1_General_CI_AI NULL,
	CONSTRAINT PK_HISTORICOFORMACOBRANCA PRIMARY KEY (HISTORICOFORMACOBRANCAID)
) GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_INDEX_00001 ON dbo.HISTORICOFORMACOBRANCA (  INSCRICAOID ASC  , COMPETENCIAINICIAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_INDEX_00002 ON dbo.HISTORICOFORMACOBRANCA (  INSCRICAOID ASC  , PRIMARIA_FORMACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_INDEX_00003 ON dbo.HISTORICOFORMACOBRANCA (  TIPORUBRICACOBRANCAID ASC  , FUNCIONARIOORGAOCONSIGNANTEID ASC  , COMPETENCIAFINAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_INDEX_00004 ON dbo.HISTORICOFORMACOBRANCA (  TIPORUBRICACOBRANCAID ASC  , FUNCIONARIOORGAOCONSIGNANTEID ASC  , INSCRICAOID ASC  , COMPETENCIAFINAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_INSCRICAOID_COMPETENCIAFINAL ON dbo.HISTORICOFORMACOBRANCA (  INSCRICAOID ASC  , COMPETENCIAFINAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_INSCRICAOID_COMPETENCIAINICIAL ON dbo.HISTORICOFORMACOBRANCA (  INSCRICAOID ASC  , COMPETENCIAINICIAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_PRIMARIA_FORMACOBRANCAID_COMPETENCIAFINAL ON dbo.HISTORICOFORMACOBRANCA (  PRIMARIA_FORMACOBRANCAID ASC  , COMPETENCIAFINAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_PRIMARIA_FORMACOBRANCAID_CONVENIOID_DIAVENCIMENTO_INSCRICAOID_PERIODICIDADEID ON dbo.HISTORICOFORMACOBRANCA (  PRIMARIA_FORMACOBRANCAID ASC  , CONVENIOID ASC  , DIAVENCIMENTO ASC  , INSCRICAOID ASC  , PERIODICIDADEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_PRIMARIA_FORMACOBRANCAID_CONVENIOID_DIAVENCIMENTO_PERIODICIDADEID ON dbo.HISTORICOFORMACOBRANCA (  PRIMARIA_FORMACOBRANCAID ASC  , CONVENIOID ASC  , DIAVENCIMENTO ASC  , PERIODICIDADEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX HISTORICOFORMACOBRANCA_PRIMARIA_FORMACOBRANCAID_FUNCIONARIOORGAOCONSIGNANTE_COMPETENCIAFINAL ON dbo.HISTORICOFORMACOBRANCA (  PRIMARIA_FORMACOBRANCAID ASC  , FUNCIONARIOORGAOCONSIGNANTEID ASC  , COMPETENCIAFINAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_CONTACORRENTE ON dbo.HISTORICOFORMACOBRANCA (  CONTACORRENTEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_CONVENIO ON dbo.HISTORICOFORMACOBRANCA (  CONVENIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_FORMACOBRANCAPRIMARIA ON dbo.HISTORICOFORMACOBRANCA (  PRIMARIA_FORMACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_FORMACOBRANCASECUNDARIA ON dbo.HISTORICOFORMACOBRANCA (  SECUNDARIA_FORMACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_FUNCIONARIOORGAOCONSIGNANTE ON dbo.HISTORICOFORMACOBRANCA (  FUNCIONARIOORGAOCONSIGNANTEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_INSCRICAO ON dbo.HISTORICOFORMACOBRANCA (  INSCRICAOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_ORGAOCONSIGNANTE ON dbo.HISTORICOFORMACOBRANCA (  ORGAOCONSIGNANTEDEBITOCONTA_PESSOAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_TIPOAGRUPAMENTOCOBRANCA ON dbo.HISTORICOFORMACOBRANCA (  TIPOAGRUPAMENTOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_TIPOPERIODICIDADE ON dbo.HISTORICOFORMACOBRANCA (  PERIODICIDADEID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_HISTORICOFORMACOBRANCA_TIPORUBRICACOBRANCA ON dbo.HISTORICOFORMACOBRANCA (  TIPORUBRICACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.HISTORICOFORMACOBRANCA foreign keys

ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_CONVENIO FOREIGN KEY (CONVENIOID) REFERENCES ESIM.dbo.CONVENIO(CONVENIOID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_FORMACOBRANCAPRIMARIA FOREIGN KEY (PRIMARIA_FORMACOBRANCAID) REFERENCES ESIM.dbo.FORMACOBRANCA(FORMACOBRANCAID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_FORMACOBRANCASECUNDARIA FOREIGN KEY (SECUNDARIA_FORMACOBRANCAID) REFERENCES ESIM.dbo.FORMACOBRANCA(FORMACOBRANCAID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_INSCRICAO FOREIGN KEY (INSCRICAOID) REFERENCES ESIM.dbo.INSCRICAO(INSCRICAOID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_ORGAOCONSIGNANTE FOREIGN KEY (ORGAOCONSIGNANTEDEBITOCONTA_PESSOAID) REFERENCES ESIM.dbo.ORGAOCONSIGNANTE(ORGAOCONSIGNANTE_PESSOAID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_TIPOAGRUPAMENTOCOBRANCA FOREIGN KEY (TIPOAGRUPAMENTOCOBRANCAID) REFERENCES ESIM.dbo.TIPOAGRUPAMENTOCOBRANCA(TIPOAGRUPAMENTOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_TIPOPERIODICIDADE FOREIGN KEY (PERIODICIDADEID) REFERENCES ESIM.dbo.TIPOPERIODICIDADE(PERIODICIDADEID) GO
ALTER TABLE ESIM.dbo.HISTORICOFORMACOBRANCA ADD CONSTRAINT FK_HISTORICOFORMACOBRANCA_TIPORUBRICACOBRANCA FOREIGN KEY (TIPORUBRICACOBRANCAID) REFERENCES ESIM.dbo.TIPORUBRICACOBRANCA(TIPORUBRICACOBRANCAID) GO;