-- ESIM.dbo.LOTENEGOCIOCOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.LOTENEGOCIOCOBRANCA GO

CREATE TABLE ESIM.dbo.LOTENEGOCIOCOBRANCA (
	LOTENEGOCIOCOBRANCAID bigint IDENTITY(1,1) NOT NULL,
	STATUSLOTENEGOCIOID smallint NOT NULL,
	LOTEMOVIMENTACAOCOBRANCAID bigint NULL,
	TIPOORIGEMCOBRANCAID smallint NOT NULL,
	CONVENIOID smallint NOT NULL,
	DATACRIACAO date NULL,
	ENVIAMAQUINAIMPRESSAO numeric(1,0) NULL,
	DATAENVIOCADASTROOPTANTE date NULL,
	CONSTRAINT PK_LOTENEGOCIOCOBRANCA PRIMARY KEY (LOTENEGOCIOCOBRANCAID)
) GO
 CREATE NONCLUSTERED INDEX IX_FK_LOTENEGOCIOCOBRANCA_CONVENIO ON dbo.LOTENEGOCIOCOBRANCA (  CONVENIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_LOTENEGOCIOCOBRANCA_LOTEMOVIMENTACAOCOBRANCA ON dbo.LOTENEGOCIOCOBRANCA (  LOTEMOVIMENTACAOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_LOTENEGOCIOCOBRANCA_STATUSLOTENEGOCIO ON dbo.LOTENEGOCIOCOBRANCA (  STATUSLOTENEGOCIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_LOTENEGOCIOCOBRANCA_TIPOORIGEMCOBRANCA ON dbo.LOTENEGOCIOCOBRANCA (  TIPOORIGEMCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.LOTENEGOCIOCOBRANCA foreign keys

ALTER TABLE ESIM.dbo.LOTENEGOCIOCOBRANCA ADD CONSTRAINT FK_LOTENEGOCIOCOBRANCA_CONVENIO FOREIGN KEY (CONVENIOID) REFERENCES ESIM.dbo.CONVENIO(CONVENIOID) GO
ALTER TABLE ESIM.dbo.LOTENEGOCIOCOBRANCA ADD CONSTRAINT FK_LOTENEGOCIOCOBRANCA_LOTEMOVIMENTACAOCOBRANCA FOREIGN KEY (LOTEMOVIMENTACAOCOBRANCAID) REFERENCES ESIM.dbo.LOTEMOVIMENTACAOCOBRANCA(LOTEMOVIMENTACAOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.LOTENEGOCIOCOBRANCA ADD CONSTRAINT FK_LOTENEGOCIOCOBRANCA_STATUSLOTENEGOCIO FOREIGN KEY (STATUSLOTENEGOCIOID) REFERENCES ESIM.dbo.STATUSLOTENEGOCIO(STATUSLOTENEGOCIOID) GO
ALTER TABLE ESIM.dbo.LOTENEGOCIOCOBRANCA ADD CONSTRAINT FK_LOTENEGOCIOCOBRANCA_TIPOORIGEMCOBRANCA FOREIGN KEY (TIPOORIGEMCOBRANCAID) REFERENCES ESIM.dbo.TIPOORIGEMCOBRANCA(TIPOORIGEMCOBRANCAID) GO;