-- ESIM.dbo.STATUSCOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.STATUSCOBRANCA GO

CREATE TABLE ESIM.dbo.STATUSCOBRANCA (
	STATUSCOBRANCAID smallint NOT NULL,
	SIGLA varchar(20) COLLATE Latin1_General_CI_AI NULL,
	DESCRICAO varchar(100) COLLATE Latin1_General_CI_AI NULL,
	ORDEMAPRESENTACAO smallint NULL,
	EXCLUIDO smallint NULL,
	CONSTRAINT PK_STATUSCOBRANCA PRIMARY KEY (STATUSCOBRANCAID)
) GO;