-- ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA GO

CREATE TABLE ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA (
	COBRANCALOTEMOVIMENTACAOCOBRANCAID bigint IDENTITY(1,1) NOT NULL,
	COBRANCAID bigint NOT NULL,
	TIPOORIGEMCOBRANCAID smallint NULL,
	LOTEMOVIMENTACAOCOBRANCAID bigint NOT NULL,
	VALORPAGO numeric(14,2) NULL,
	VALORIOFRETIDO numeric(14,2) NULL,
	DATAPAGAMENTO date NULL,
	RATEIOREALIZADO numeric(1,0) NULL,
	CODIGORETORNOCONVENIOID int NULL,
	BANCOPAGAMENTOBOLETO int NULL,
	APROPRIADO numeric(1,0) DEFAULT 0 NULL,
	CONSTRAINT PK_COBRANCALOTEMOVIMENTACAOCOBRANCA PRIMARY KEY (COBRANCALOTEMOVIMENTACAOCOBRANCAID)
) GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCALOTEMOVIMENTACAOCOBRANCA_COBRANCA ON dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA (  COBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCALOTEMOVIMENTACAOCOBRANCA_LOTEMOVIMENTACAOCOBRANCA ON dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA (  LOTEMOVIMENTACAOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCALOTEMOVIMENTACAOCOBRANCA_TIPOORIGEMCOBRANCA ON dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA (  TIPOORIGEMCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA foreign keys

ALTER TABLE ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA ADD CONSTRAINT FK_COBRANCALOTEMOVIMENTACAOCOBRANCA_COBRANCA FOREIGN KEY (COBRANCAID) REFERENCES ESIM.dbo.COBRANCA(COBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA ADD CONSTRAINT FK_COBRANCALOTEMOVIMENTACAOCOBRANCA_LOTEMOVIMENTACAOCOBRANCA FOREIGN KEY (LOTEMOVIMENTACAOCOBRANCAID) REFERENCES ESIM.dbo.LOTEMOVIMENTACAOCOBRANCA(LOTEMOVIMENTACAOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCALOTEMOVIMENTACAOCOBRANCA ADD CONSTRAINT FK_COBRANCALOTEMOVIMENTACAOCOBRANCA_TIPOORIGEMCOBRANCA FOREIGN KEY (TIPOORIGEMCOBRANCAID) REFERENCES ESIM.dbo.TIPOORIGEMCOBRANCA(TIPOORIGEMCOBRANCAID) GO;