-- ESIM.dbo.COBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.COBRANCA GO

CREATE TABLE COBRANCA (
	COBRANCAID bigint prymary key NOT NULL auto_increment,
	TIPOCOBRANCAID smallint NOT NULL,
	HISTORICOCOBRANCAID bigint NULL,
	STATUSCOBRANCAID smallint NOT NULL,
	LOTENEGOCIOCOBRANCAID bigint NULL,
	VALORCOBRADO numeric(14,2) NOT NULL,
	DATAVENCIMENTO date NULL,
	IDENTIFICACAOEXTERNA bigint NULL,
	NOSSONUMERO bigint NULL,
	DVNOSSONUMERO varchar(1) COLLATE Latin1_General_CI_AI NULL,
	ENDERECOSACADO varchar(200) COLLATE Latin1_General_CI_AI NULL,
	NOMESACADO varchar(200) COLLATE Latin1_General_CI_AI NULL,
	DOCUMENTOSACADO varchar(14) COLLATE Latin1_General_CI_AI NULL,
	INSTRUCAO1 varchar(100) COLLATE Latin1_General_CI_AI NULL,
	INSTRUCAO2 varchar(100) COLLATE Latin1_General_CI_AI NULL,
	INSTRUCAO3 varchar(100) COLLATE Latin1_General_CI_AI NULL,
	INSTRUCAO4 varchar(100) COLLATE Latin1_General_CI_AI NULL,
	VALORIOF numeric(14,2) NULL,
	NUMEROAGENCIA int NULL,
	NUMEROCONTACORRENTE bigint NULL,
	DVCONTACORRENTE varchar(2) COLLATE Latin1_General_CI_AI NULL,
	DVAGENCIA varchar(2) COLLATE Latin1_General_CI_AI NULL,
	NUMEROSACADO int NULL,
	COMPLEMENTOSACADO varchar(20) COLLATE Latin1_General_CI_AI NULL,
	BAIRROSACADO varchar(50) COLLATE Latin1_General_CI_AI NULL,
	CIDADESACADO varchar(50) COLLATE Latin1_General_CI_AI NULL,
	CEPSACADO int NULL,
	UFSACADO varchar(2) COLLATE Latin1_General_CI_AI NULL,
	EMAILSACADO varchar(200) COLLATE Latin1_General_CI_AI NULL,
	IDENTIFICADORCARTAOCREDITO bigint NULL,
	LINHADIGITAVEL varchar(54) COLLATE Latin1_General_CI_AI NULL,
	CODIGOBARRA varchar(44) COLLATE Latin1_General_CI_AI NULL,
	DVNOSSONUMEROREMESSA varchar(1) COLLATE Latin1_General_CI_AI NULL,
	NOSSONUMEROREMESSA int NULL,
	TRANSACAOCARTAOCREDITO varchar(50) COLLATE Latin1_General_CI_AI NULL,
	DATAPAGAMENTOADQUIRENTE date NULL,
	VALORCUSTO decimal(14,2) NULL,
	CONSTRAINT PK_COBRANCA PRIMARY KEY (COBRANCAID)
) GO
 CREATE  UNIQUE NONCLUSTERED INDEX COBRANCA_TRANSACAOCARTAOCREDITO ON dbo.COBRANCA (  TRANSACAOCARTAOCREDITO ASC  )  
	 WHERE  ([TRANSACAOCARTAOCREDITO] IS NOT NULL)
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE  UNIQUE NONCLUSTERED INDEX IN_AK_COBRANCA ON dbo.COBRANCA (  NOSSONUMERO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IN_COBRANCA_AGENCIA_CONTA ON dbo.COBRANCA (  NUMEROAGENCIA ASC  , NUMEROCONTACORRENTE ASC  , DVCONTACORRENTE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IN_IDENTIFICACAOEXTERNA ON dbo.COBRANCA (  IDENTIFICACAOEXTERNA ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCA_HISTORICOCOBRANCA ON dbo.COBRANCA (  HISTORICOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCA_LOTENEGOCIOCOBRANCA ON dbo.COBRANCA (  LOTENEGOCIOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCA_STATUSCOBRANCA ON dbo.COBRANCA (  STATUSCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_COBRANCA_TIPOCOBRANCA3 ON dbo.COBRANCA (  TIPOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.COBRANCA foreign keys

ALTER TABLE ESIM.dbo.COBRANCA ADD CONSTRAINT FK_COBRANCA_HISTORICOCOBRANCA FOREIGN KEY (HISTORICOCOBRANCAID) REFERENCES ESIM.dbo.HISTORICOCOBRANCA(HISTORICOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCA ADD CONSTRAINT FK_COBRANCA_LOTENEGOCIOCOBRANCA FOREIGN KEY (LOTENEGOCIOCOBRANCAID) REFERENCES ESIM.dbo.LOTENEGOCIOCOBRANCA(LOTENEGOCIOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCA ADD CONSTRAINT FK_COBRANCA_STATUSCOBRANCA FOREIGN KEY (STATUSCOBRANCAID) REFERENCES ESIM.dbo.STATUSCOBRANCA(STATUSCOBRANCAID) GO
ALTER TABLE ESIM.dbo.COBRANCA ADD CONSTRAINT FK_COBRANCA_TIPOCOBRANCA3 FOREIGN KEY (TIPOCOBRANCAID) REFERENCES ESIM.dbo.TIPOCOBRANCA3(TIPOCOBRANCAID) GO;