-- ESIM.dbo.CONVENIO definition

-- Drop table

-- DROP TABLE ESIM.dbo.CONVENIO GO

CREATE TABLE ESIM.dbo.CONVENIO (
	CONVENIOID smallint IDENTITY(1,1) NOT NULL,
	TIPOREFERENCIAVALORDIFERENCA_T smallint NULL,
	TIPOREFERENCIAVALORCONCILIAITE smallint NULL,
	CONTRATOCOBRANCAID smallint DEFAULT 1 NOT NULL,
	FORMACOBRANCAID smallint NOT NULL,
	SIGLA varchar(20) COLLATE Latin1_General_CI_AI NULL,
	DESCRICAO varchar(50) COLLATE Latin1_General_CI_AI NULL,
	SEQUENCIARETORNO int NULL,
	ENVIAARQUIVO smallint NULL,
	RECEBERETORNO smallint NULL,
	RECEBECREDITO smallint NULL,
	RECEBECRITICA smallint NULL,
	REALIZACONCILIACAOFINANCEIRA smallint NULL,
	IDENTIFICACREDITO smallint NULL,
	ACEITADIFERENCAIDENTIFICACREDI smallint NULL,
	VALORDIFERENCAIDENTIFICACREDIT numeric(5,0) NULL,
	CONCILIAITEMMOVTO smallint NULL,
	VALORDIFERENCAITEMMOVTO numeric(5,0) NULL,
	ACEITADIFERENCAITEMMOVTO smallint NULL,
	LIMITESEQUENCIARETORNO int NULL,
	SEQUENCIALCONVENIOREMESSAID smallint NULL,
	TIPOLAYOUTCARTAOCREDITORETORNOID smallint NULL,
	TIPOLAYOUTRETORNOID smallint NULL,
	TIPOLAYOUTID smallint NULL,
	TIPOLAYOUTCARTAOCREDITOID smallint NULL,
	TIPOIDENTIFICACAOCREDITOID smallint NULL,
	CONTAARRECADACAOID smallint NULL,
	CRITICA_TIPOLAYOUTRETORNOID smallint NULL,
	BANCO_PESSOAID int NULL,
	TIPOPESSOACONVENIOID smallint NULL,
	COOPERATIVA varchar(25) COLLATE Latin1_General_CI_AI NULL,
	MODALIDADE varchar(10) COLLATE Latin1_General_CI_AI NULL,
	TIPOCODIGOBARRAID smallint NULL,
	ISCOBRANCANOVO numeric(1,0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_CONVENIO PRIMARY KEY (CONVENIOID)
) GO
 CREATE  UNIQUE NONCLUSTERED INDEX AK_SIGLA_CONVENIO ON dbo.CONVENIO (  SIGLA ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX CONVENIO_INDEX_00001 ON dbo.CONVENIO (  CONVENIOID ASC  , SEQUENCIALCONVENIOREMESSAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_BANCO ON dbo.CONVENIO (  BANCO_PESSOAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_CONTAARRECADACAO ON dbo.CONVENIO (  CONTAARRECADACAOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_CONTRATOCOBRANCA ON dbo.CONVENIO (  CONTRATOCOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_FORMACOBRANCA ON dbo.CONVENIO (  FORMACOBRANCAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_SEQUENCIALCONVENIOREMESSA ON dbo.CONVENIO (  SEQUENCIALCONVENIOREMESSAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOCODIGOBARRA ON dbo.CONVENIO (  TIPOCODIGOBARRAID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOIDENTIFICACAOCREDITO ON dbo.CONVENIO (  TIPOIDENTIFICACAOCREDITOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOLAYOUT ON dbo.CONVENIO (  TIPOLAYOUTID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOLAYOUTCARTAOCREDITO ON dbo.CONVENIO (  TIPOLAYOUTCARTAOCREDITOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOLAYOUTCARTAOCREDITORETORNO ON dbo.CONVENIO (  TIPOLAYOUTCARTAOCREDITORETORNOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOLAYOUTRETORNO ON dbo.CONVENIO (  TIPOLAYOUTRETORNOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOLAYOUTRETORNOCRITICA ON dbo.CONVENIO (  CRITICA_TIPOLAYOUTRETORNOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOPESSOACONVENIO ON dbo.CONVENIO (  TIPOPESSOACONVENIOID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOREFERENCIAVALOR ON dbo.CONVENIO (  TIPOREFERENCIAVALORDIFERENCA_T ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO
 CREATE NONCLUSTERED INDEX IX_FK_CONVENIO_TIPOREFERVR ON dbo.CONVENIO (  TIPOREFERENCIAVALORCONCILIAITE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ]  GO;


-- ESIM.dbo.CONVENIO foreign keys

ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_BANCO FOREIGN KEY (BANCO_PESSOAID) REFERENCES ESIM.dbo.BANCO(PESSOAID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_CONTAARRECADACAO FOREIGN KEY (CONTAARRECADACAOID) REFERENCES ESIM.dbo.CONTAARRECADACAO(CONTAARRECADACAOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_CONTRATOCOBRANCA FOREIGN KEY (CONTRATOCOBRANCAID) REFERENCES ESIM.dbo.CONTRATOCOBRANCA(CONTRATOCOBRANCAID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_FORMACOBRANCA FOREIGN KEY (FORMACOBRANCAID) REFERENCES ESIM.dbo.FORMACOBRANCA(FORMACOBRANCAID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_SEQUENCIALCONVENIOREMESSA FOREIGN KEY (SEQUENCIALCONVENIOREMESSAID) REFERENCES ESIM.dbo.SEQUENCIALCONVENIOREMESSA(SEQUENCIALCONVENIOREMESSAID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOCODIGOBARRA FOREIGN KEY (TIPOCODIGOBARRAID) REFERENCES ESIM.dbo.TIPOCODIGOBARRA(TIPOCODIGOBARRAID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOIDENTIFICACAOCREDITO FOREIGN KEY (TIPOIDENTIFICACAOCREDITOID) REFERENCES ESIM.dbo.TIPOIDENTIFICACAOCREDITO(TIPOIDENTIFICACAOCREDITOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOLAYOUT FOREIGN KEY (TIPOLAYOUTID) REFERENCES ESIM.dbo.TIPOLAYOUT(TIPOLAYOUTID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOLAYOUTCARTAOCREDITO FOREIGN KEY (TIPOLAYOUTCARTAOCREDITOID) REFERENCES ESIM.dbo.TIPOLAYOUTCARTAOCREDITO(TIPOLAYOUTCARTAOCREDITOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOLAYOUTCARTAOCREDITORETORNO FOREIGN KEY (TIPOLAYOUTCARTAOCREDITORETORNOID) REFERENCES ESIM.dbo.TIPOLAYOUTCARTAOCREDITORETORNO(TIPOLAYOUTCARTAOCREDITORETORNOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOLAYOUTRETORNO FOREIGN KEY (TIPOLAYOUTRETORNOID) REFERENCES ESIM.dbo.TIPOLAYOUTRETORNO(TIPOLAYOUTRETORNOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOLAYOUTRETORNOCRITICA FOREIGN KEY (CRITICA_TIPOLAYOUTRETORNOID) REFERENCES ESIM.dbo.TIPOLAYOUTRETORNO(TIPOLAYOUTRETORNOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOPESSOACONVENIO FOREIGN KEY (TIPOPESSOACONVENIOID) REFERENCES ESIM.dbo.TIPOPESSOACONVENIO(TIPOPESSOACONVENIOID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOREFERENCIAVALOR FOREIGN KEY (TIPOREFERENCIAVALORDIFERENCA_T) REFERENCES ESIM.dbo.TIPOREFERENCIAVALOR(TIPOREFERENCIAVALORID) GO
ALTER TABLE ESIM.dbo.CONVENIO ADD CONSTRAINT FK_CONVENIO_TIPOREFERVR FOREIGN KEY (TIPOREFERENCIAVALORCONCILIAITE) REFERENCES ESIM.dbo.TIPOREFERENCIAVALOR(TIPOREFERENCIAVALORID) GO;