-- ESIM.dbo.HISTORICOCOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.HISTORICOCOBRANCA GO

CREATE TABLE HISTORICOCOBRANCA (
	HISTORICOCOBRANCAID int prymary key  NOT NULL auto_increment,
	CONSTRAINT PK_HISTORICOCOBRANCA PRIMARY KEY (HISTORICOCOBRANCAID)
) GO;