-- ESIM.dbo.TIPOORIGEMCOBRANCA definition

-- Drop table

-- DROP TABLE ESIM.dbo.TIPOORIGEMCOBRANCA GO

CREATE TABLE ESIM.dbo.TIPOORIGEMCOBRANCA (
	TIPOORIGEMCOBRANCAID smallint NOT NULL,
	SIGLA varchar(20) COLLATE Latin1_General_CI_AI NULL,
	DESCRICAO varchar(100) COLLATE Latin1_General_CI_AI NULL,
	ORDEMAPRESENTACAO smallint NULL,
	EXCLUIDO smallint NULL,
	CONSTRAINT PK_TIPOORIGEMCOBRANCA PRIMARY KEY (TIPOORIGEMCOBRANCAID)
) GO;