<?php

namespace App\Traits;

trait BankArrayTrait
{
    /**
     * Lista de bancos brasileiros em array. Modo de usar:
     * 
     * array_rand($this->getBanks());
     * array_random($this->getBanks());
     * */

    public function getBanks()
    {
        $banks = [
            'Banco do Brasil' => '001',
            'Banco da Amazônia' => '003',
            'Banco do Nordeste' => '004',
            'Banestes' => '021',
            'Banco Alfa' => '025',
            'Besc' => '027',
            'Banerj' => '029',
            'Banco Beg' => '031',
            'Banco Santander Banespa' => '033',
            'Banco Bem' => '036',
            'Banpará' => '037',
            'Banestado' => '038',
            'BEP' => '039',
            'Banco Cargill' => '040',
            'Banrisul' => '041',
            'BVA' => '044',
            'Banco Opportunity' => '045',
            'Banese' => '047',
            'Hipercard' => '062',
            'Ibibank' => '063',
            'Lemon Bank' => '065',
            'Banco Morgan Stanley Dean Witter' => '066',
            'BPN Brasil' => '069',
            'Banco de Brasília – BRB' => '070',
            'Banco Rural' => '072',
            'Banco Popular' => '073',
            'Banco J. Safra' => '074',
            'Banco CR2' => '075',
            'Banco KDB' => '076',
            'Banco BMF' => '096',
            'Caixa Econômica Federal' => '104',
            'Banco BBM' => '107',
            'Banco Único' => '116',
            'Nossa Caixa' => '151',
            'Banco Finasa' => '175',
            'Banco Itaú BBA' => '184',
            'American Express Bank' => '204',
            'Banco Pactual' => '208',
            'Banco Matone' => '212',
            'Banco Arbi' => '213',
            'Banco Dibens' => '214',
            'Banco Joh Deere' => '217',
            'Banco Bonsucesso' => '218',
            'Banco Calyon Brasil' => '222',
            'Banco Fibra' => '224',
            'Banco Brascan' => '225',
            'Banco Cruzeiro' => '229',
            'Unicard' => '230',
            'Banco GE Capital' => '233',
            'Bradesco' => '237',
            'Banco Clássico' => '241',
            'Banco Stock Máxima' => '243',
            'Banco ABC Brasil' => '246',
            'Banco Boavista Interatlântico' => '248',
            'Investcred Unibanco' => '249',
            'Banco Schahin' => '250',
            'Fininvest' => '252',
            'Paraná Banco' => '254',
            'Banco Cacique' => '263',
            'Banco Fator' => '265',
            'Banco Cédula' => '266',
            'Banco de la Nación Argentina' => '300',
            'Banco BMG' => '318',
            'Banco Industrial e Comercial' => '320',
            'ABN Amro Real' => '356',
            'Itau' => '341',
            'Sudameris' => '347',
            'Banco Santander' => '351',
            'Banco Santander Brasil' => '353',
            'Banco Societe Generale Brasil' => '366',
            'Banco WestLB' => '370',
            'JP Morgan' => '376',
            'Banco Mercantil do Brasil' => '389',
            'Banco Mercantil de Crédito' => '394',
            'HSBC' => '399',
            'Unibanco' => '409',
            'Banco Capital' => '412',
            'Banco Safra' => '422',
            'Banco Tokyo Mitsubishi UFJ' => '456',
            'Banco Sumitomo Mitsui Brasileiro' => '464',
            'Citibank' => '477',
            'Itaubank (antigo Bank Boston)' => '479',
            'Deutsche Bank' => '487',
            'Banco Morgan Guaranty' => '488',
            'Banco NMB Postbank' => '492',
            'Banco la República Oriental del Uruguay' => '494',
            'Banco La Provincia de Buenos Aires' => '495',
            'Banco Credit Suisse' => '505',
            'Banco Luso Brasileiro' => '600',
            'Banco Industrial' => '604',
            'Banco VR' => '610',
            'Banco Paulista' => '611',
            'Banco Guanabara' => '612',
            'Banco Pecunia' => '613',
            'Banco Panamericano' => '623',
            'Banco Ficsa' => '626',
            'Banco Intercap' => '630',
            'Banco Rendimento' => '633',
            'Banco Triângulo' => '634',
            'Banco Sofisa' => '637',
            'Banco Prosper' => '638',
            'Banco Pine' => '643',
            'Itaú Holding Financeira' => '652',
            'Banco Indusval' => '653',
            'Banco A.J. Renner' => '654',
            'Banco Votorantim' => '655',
            'Banco Daycoval' => '707',
            'Banif' => '719',
            'Banco Credibel' => '721',
            'Banco Gerdau' => '734',
            'Banco Pottencial' => '735',
            'Banco Morada' => '738',
            'Banco Galvão de Negócios' => '739',
            'Banco Barclays' => '740',
            'BRP' => '741',
            'Banco Semear' => '743',
            'Banco Citibank' => '745',
            'Banco Modal' => '746',
            'Banco Rabobank International' => '747',
            'Banco Cooperativo Sicredi' => '748',
            'Banco Simples' => '749',
            'Dresdner Bank' => '751',
            'BNP Paribas' => '752',
            'Banco Comercial Uruguai' => '753',
            'Banco Merrill Lynch' => '755',
            'Banco Cooperativo do Brasil' => '756',
            'KEB' => '757'
        ];

        return $banks;
    }
}